package server
import "net/http"
func(s *Server)dashboard(w http.ResponseWriter,r *http.Request){w.Header().Set("Content-Type","text/html; charset=utf-8");w.Write([]byte(dashHTML))}
const dashHTML=`<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Watcher</title>
<style>:root{--bg:#1a1410;--bg2:#241e18;--bg3:#2e261e;--rust:#c45d2c;--rl:#e8753a;--leather:#a0845c;--cream:#f0e6d3;--cd:#bfb5a3;--cm:#7a7060;--gold:#d4a843;--green:#4a9e5c;--mono:'JetBrains Mono',Consolas,monospace;--serif:'Libre Baskerville',Georgia,serif}*{margin:0;padding:0;box-sizing:border-box}body{background:var(--bg);color:var(--cream);font-family:var(--mono);font-size:13px;line-height:1.6}.hdr{padding:.6rem 1.2rem;border-bottom:1px solid var(--bg3);display:flex;justify-content:space-between;align-items:center}.hdr h1{font-family:var(--serif);font-size:1rem}.hdr h1 span{color:var(--rl)}.main{max-width:700px;margin:0 auto;padding:1rem}.btn{font-family:var(--mono);font-size:.68rem;padding:.3rem .6rem;border:1px solid;cursor:pointer;background:transparent}.btn-p{border-color:var(--rust);color:var(--rl)}.btn-p:hover{background:var(--rust);color:var(--cream)}.card{background:var(--bg2);border:1px solid var(--bg3);padding:.6rem;margin-bottom:.4rem;cursor:pointer;transition:.1s}.card:hover{background:var(--bg3)}.card h3{font-size:.8rem;margin-bottom:.15rem}.card-meta{font-size:.65rem;color:var(--cm);display:flex;gap:.7rem}.toggle{width:36px;height:20px;border-radius:10px;cursor:pointer;position:relative;transition:.2s}.toggle.on{background:var(--green)}.toggle.off{background:var(--bg3)}.toggle::after{content:'';width:16px;height:16px;border-radius:50%;background:var(--cream);position:absolute;top:2px;left:2px;transition:.2s}.toggle.on::after{left:18px}.change-row{font-size:.72rem;padding:.25rem .5rem;border-bottom:1px solid var(--bg3);display:flex;gap:.5rem}.empty{text-align:center;padding:2rem;color:var(--cm);font-style:italic;font-family:var(--serif)}.modal-bg{position:fixed;top:0;left:0;right:0;bottom:0;background:rgba(0,0,0,.65);display:flex;align-items:center;justify-content:center;z-index:100}.modal{background:var(--bg2);border:1px solid var(--bg3);padding:1.5rem;width:90%;max-width:450px}.modal h2{font-family:var(--serif);font-size:.9rem;margin-bottom:1rem}label.fl{display:block;font-size:.65rem;color:var(--leather);text-transform:uppercase;letter-spacing:1px;margin-bottom:.2rem;margin-top:.5rem}input[type=text]{background:var(--bg);border:1px solid var(--bg3);color:var(--cream);padding:.35rem .5rem;font-family:var(--mono);font-size:.78rem;width:100%;outline:none}</style>
<link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville:ital@0;1&family=JetBrains+Mono:wght@400;600&display=swap" rel="stylesheet">
</head><body><div class="hdr"><h1><span>Watcher</span></h1><button class="btn btn-p" onclick="showNew()">+ Watch</button></div>
<div class="main"><div id="list"></div><div id="detail" style="display:none;margin-top:1rem"></div></div><div id="modal"></div>
<script>
async function api(u,o){return(await fetch(u,o)).json()}
function esc(s){return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
function timeAgo(d){if(!d)return'never';const s=Math.floor((Date.now()-new Date(d))/1e3);if(s<60)return s+'s ago';if(s<3600)return Math.floor(s/60)+'m ago';return Math.floor(s/3600)+'h ago'}
async function load(){const d=await api('/api/watches');const ws=d.watches||[];
document.getElementById('list').innerHTML=ws.length?ws.map(w=>'<div class="card" onclick="open_(\''+w.id+'\')"><div style="display:flex;align-items:center;gap:.5rem"><div class="toggle '+(w.enabled?'on':'off')+'" onclick="event.stopPropagation();toggle(\''+w.id+'\')"></div><h3>'+(w.name||w.path)+'</h3></div><div class="card-meta"><span>'+esc(w.path)+'</span><span>'+w.change_count+' changes</span><span>last: '+timeAgo(w.last_change)+'</span></div></div>').join(''):'<div class="empty">No watches configured.</div>'}
async function open_(id){const[w,cd]=await Promise.all([api('/api/watches/'+id),api('/api/watches/'+id+'/changes')]);
const changes=(cd.changes||[]).map(c=>'<div class="change-row"><span style="color:var(--gold);width:60px">'+c.action+'</span><span style="flex:1">'+esc(c.file_name)+'</span><span style="color:var(--cm)">'+c.size+'B</span><span style="color:var(--cm)">'+timeAgo(c.created_at)+'</span></div>').join('');
document.getElementById('detail').style.display='block';
document.getElementById('detail').innerHTML='<div style="display:flex;justify-content:space-between;margin-bottom:.5rem"><span style="font-size:.75rem;color:var(--leather)">'+esc(w.name||w.path)+'</span><button class="btn" style="border-color:var(--bg3);color:var(--cm)" onclick="del(\''+id+'\')">Del</button></div>'+(changes||'<div class="empty" style="padding:1rem">No changes detected yet.</div>')}
async function toggle(id){await api('/api/watches/'+id+'/toggle',{method:'POST'});load()}
async function del(id){await api('/api/watches/'+id,{method:'DELETE'});document.getElementById('detail').style.display='none';load()}
function showNew(){document.getElementById('modal').innerHTML='<div class="modal-bg" onclick="if(event.target===this)closeModal()"><div class="modal"><h2>New Watch</h2><label class="fl">Path</label><input type="text" id="nw-path" placeholder="/var/log/app.log"><label class="fl">Name (optional)</label><input type="text" id="nw-name" placeholder="App log"><label class="fl">Webhook URL (optional)</label><input type="text" id="nw-hook" placeholder="https://hooks.slack.com/..."><div style="display:flex;gap:.5rem;margin-top:1rem"><button class="btn btn-p" onclick="save()">Create</button><button class="btn" style="border-color:var(--bg3);color:var(--cm)" onclick="closeModal()">Cancel</button></div></div></div>'}
async function save(){const b={path:document.getElementById('nw-path').value,name:document.getElementById('nw-name').value,webhook_url:document.getElementById('nw-hook').value};if(!b.path){alert('Path required');return};await api('/api/watches',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});closeModal();load()}
function closeModal(){document.getElementById('modal').innerHTML=''}
load();setInterval(load,10000)
</script></body></html>`
