package store
import("database/sql";"fmt";"os";"path/filepath";"time";_ "modernc.org/sqlite")
type DB struct{*sql.DB}
type Monitor struct{ID int64 `json:"id"`;Name string `json:"name"`;URL string `json:"url"`;Method string `json:"method"`;IntervalSec int `json:"interval_sec"`;TimeoutSec int `json:"timeout_sec"`;ExpectStatus int `json:"expect_status"`;Status string `json:"status"`;LastChecked *time.Time `json:"last_checked"`;LastLatencyMs int `json:"last_latency_ms"`;UptimePct float64 `json:"uptime_pct"`;CreatedAt time.Time `json:"created_at"`}
type CheckResult struct{ID int64 `json:"id"`;MonitorID int64 `json:"monitor_id"`;Status string `json:"status"`;LatencyMs int `json:"latency_ms"`;StatusCode int `json:"status_code"`;Error string `json:"error"`;CreatedAt time.Time `json:"created_at"`}
func Open(dataDir string)(*DB,error){if err:=os.MkdirAll(dataDir,0755);err!=nil{return nil,fmt.Errorf("mkdir: %w",err)};dsn:=filepath.Join(dataDir,"watcher.db")+"?_journal_mode=WAL&_busy_timeout=5000";db,err:=sql.Open("sqlite",dsn);if err!=nil{return nil,fmt.Errorf("open: %w",err)};db.SetMaxOpenConns(1);if err:=migrate(db);err!=nil{return nil,fmt.Errorf("migrate: %w",err)};return &DB{db},nil}
func migrate(db *sql.DB)error{_,err:=db.Exec(`CREATE TABLE IF NOT EXISTS monitors(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,url TEXT NOT NULL,method TEXT DEFAULT 'GET',interval_sec INTEGER DEFAULT 60,timeout_sec INTEGER DEFAULT 10,expect_status INTEGER DEFAULT 200,status TEXT DEFAULT 'unknown',last_checked DATETIME,last_latency_ms INTEGER DEFAULT 0,uptime_pct REAL DEFAULT 0,created_at DATETIME DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS check_results(id INTEGER PRIMARY KEY AUTOINCREMENT,monitor_id INTEGER NOT NULL,status TEXT NOT NULL,latency_ms INTEGER DEFAULT 0,status_code INTEGER DEFAULT 0,error TEXT DEFAULT '',created_at DATETIME DEFAULT CURRENT_TIMESTAMP);CREATE INDEX IF NOT EXISTS cr_monitor ON check_results(monitor_id,created_at DESC);`);return err}
func(db *DB)ListMonitors()([]Monitor,error){rows,err:=db.Query(`SELECT id,name,url,method,interval_sec,timeout_sec,expect_status,status,last_checked,last_latency_ms,uptime_pct,created_at FROM monitors ORDER BY name`);if err!=nil{return nil,err};defer rows.Close();var out[]Monitor;for rows.Next(){var m Monitor;rows.Scan(&m.ID,&m.Name,&m.URL,&m.Method,&m.IntervalSec,&m.TimeoutSec,&m.ExpectStatus,&m.Status,&m.LastChecked,&m.LastLatencyMs,&m.UptimePct,&m.CreatedAt);out=append(out,m)};return out,nil}
func(db *DB)CreateMonitor(m *Monitor)error{if m.Method==""{m.Method="GET"};if m.IntervalSec==0{m.IntervalSec=60};if m.TimeoutSec==0{m.TimeoutSec=10};if m.ExpectStatus==0{m.ExpectStatus=200};res,err:=db.Exec(`INSERT INTO monitors(name,url,method,interval_sec,timeout_sec,expect_status)VALUES(?,?,?,?,?,?)`,m.Name,m.URL,m.Method,m.IntervalSec,m.TimeoutSec,m.ExpectStatus);if err!=nil{return err};m.ID,_=res.LastInsertId();m.Status="unknown";return nil}
func(db *DB)DeleteMonitor(id int64)error{_,err:=db.Exec(`DELETE FROM monitors WHERE id=?`,id);_,_=db.Exec(`DELETE FROM check_results WHERE monitor_id=?`,id);return err}
func(db *DB)RecordCheck(monitorID int64,status string,latencyMs,statusCode int,errMsg string){db.Exec(`INSERT INTO check_results(monitor_id,status,latency_ms,status_code,error)VALUES(?,?,?,?,?)`,monitorID,status,latencyMs,statusCode,errMsg);uptime:=0.0;var total,up int;db.QueryRow(`SELECT COUNT(*),SUM(CASE WHEN status='up' THEN 1 ELSE 0 END) FROM check_results WHERE monitor_id=? AND created_at>datetime('now','-24 hours')`,monitorID).Scan(&total,&up);if total>0{uptime=float64(up)/float64(total)*100};db.Exec(`UPDATE monitors SET status=?,last_checked=CURRENT_TIMESTAMP,last_latency_ms=?,uptime_pct=? WHERE id=?`,status,latencyMs,uptime,monitorID)}
func(db *DB)GetHistory(monitorID int64,limit int)([]CheckResult,error){if limit==0{limit=50};rows,err:=db.Query(`SELECT id,monitor_id,status,latency_ms,status_code,error,created_at FROM check_results WHERE monitor_id=? ORDER BY created_at DESC LIMIT ?`,monitorID,limit);if err!=nil{return nil,err};defer rows.Close();var out[]CheckResult;for rows.Next(){var c CheckResult;rows.Scan(&c.ID,&c.MonitorID,&c.Status,&c.LatencyMs,&c.StatusCode,&c.Error,&c.CreatedAt);out=append(out,c)};return out,nil}
func(db *DB)CountMonitors()(int,error){var n int;db.QueryRow(`SELECT COUNT(*) FROM monitors`).Scan(&n);return n,nil}
func(db *DB)CountDown()(int,error){var n int;db.QueryRow(`SELECT COUNT(*) FROM monitors WHERE status='down'`).Scan(&n);return n,nil}
