name: Docker
on:
  push:
    tags: ['v*']
jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/stockyard-dev/stockyard-watcher:latest,ghcr.io/stockyard-dev/stockyard-watcher:${{ github.ref_name }}
